In [1]:
import pandas as pd
import numpy as np

# Importing data from G Drive

In [2]:
train=pd.read_csv('C:/Users/sanjay.garje/Desktop/sanjay.garje/datacamp/Titanic/train.csv')
test = pd.read_csv('C:/Users/sanjay.garje/Desktop/sanjay.garje/datacamp/Titanic/test.csv')

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

## EDA

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [6]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
train["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [8]:
test.shape

(418, 11)

In [9]:
train['Age']=train['Age'].fillna(value=train.Age.mean())

In [10]:
x=train.drop('Cabin',axis=1)

In [11]:
x=x.fillna(method='ffill')

In [12]:
x_train=x.drop('Survived',axis=1)

In [13]:
y_train=x['Survived']

# EDA after handling missing values

In [14]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
PassengerId    891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB


In [15]:
x_train=x.drop(['Name','Ticket'],axis=1)

In [16]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [17]:
x_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

# Converting catagorical columns to numeric catagorical columns:

In [18]:
from sklearn.preprocessing import LabelBinarizer

In [19]:
s=LabelBinarizer()

In [20]:
j=s.fit_transform(x_train.Sex)
k=s.fit_transform(x_train.Pclass)
l=s.fit_transform(x_train.Embarked)

In [21]:
Sex1=pd.DataFrame(j,columns=['Sex_1'])

In [22]:
Emb=pd.DataFrame(l,columns=['Emb_1','Emb_2','Emb_3'])

In [23]:
Pcl=pd.DataFrame(k,columns=['Pcl_1','Pcl_2','Pcl_3'])

In [24]:
X_train=pd.concat([x_train,Sex1,Emb,Pcl],axis=1)

In [25]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null object
Sex_1          891 non-null int32
Emb_1          891 non-null int32
Emb_2          891 non-null int32
Emb_3          891 non-null int32
Pcl_1          891 non-null int32
Pcl_2          891 non-null int32
Pcl_3          891 non-null int32
dtypes: float64(2), int32(7), int64(5), object(2)
memory usage: 87.1+ KB


In [26]:
Final_tr=X_train.drop(['Sex','Embarked','Pclass'],axis=1)

In [27]:
Final_tr.head()

PassengerId  Survived   Age  SibSp  Parch     Fare  Sex_1  Emb_1  Emb_2  \
0            1         0  22.0      1      0   7.2500      1      0      0   
1            2         1  38.0      1      0  71.2833      0      1      0   
2            3         1  26.0      0      0   7.9250      0      0      0   
3            4         1  35.0      1      0  53.1000      0      0      0   
4            5         0  35.0      0      0   8.0500      1      0      0   

   Emb_3  Pcl_1  Pcl_2  Pcl_3  
0      1      0      0      1  
1      0      1      0      0  
2      1      0      0      1  
3      1      1      0      0  
4      1      0      0      1

# Spliting training set in to training and testing

In [28]:
y_final=Final_tr.Survived

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
Final=Final_tr.drop("Survived",axis=1)

In [31]:
T_train,T_test,y_tr,y_ts=train_test_split(Final,y_final,test_size=0.3,random_state=42)

# Logistic Regression model

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg=LogisticRegression()

In [34]:
logreg.fit(T_train,y_tr)

C:\Users\sanjay.garje\AppData\Local\Continuum\anaconda3\envs\data science\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [35]:
y_pr=logreg.predict(T_test)

In [36]:
LogScore=logreg.score(T_test,y_ts)

In [37]:
print(LogScore)

0.8022388059701493


In [38]:
from sklearn.metrics import confusion_matrix
conf_mat_log=confusion_matrix(y_ts,y_pr)

In [39]:
print(conf_mat_log)

[[136  21]
 [ 32  79]]


# Linear SVC model

In [40]:
from sklearn.svm import LinearSVC

In [41]:
lsvc=LinearSVC()

In [42]:
lsvc.fit(T_train,y_tr)

C:\Users\sanjay.garje\AppData\Local\Continuum\anaconda3\envs\data science\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [43]:
lsvc_y_pr=lsvc.predict(T_test)

In [44]:
print(lsvc_y_pr)

[0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0]


In [45]:
lsvc_score=lsvc.score(T_test,y_ts)

In [46]:
print(lsvc_score)

0.6305970149253731


In [47]:
from sklearn.metrics import confusion_matrix
conf_lvsc_score=confusion_matrix(y_ts,lsvc_y_pr)

In [48]:
print(conf_lvsc_score)

[[151   6]
 [ 93  18]]


# K Neighbor Classifier

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier(n_neighbors=3)


In [50]:
knc.fit(T_train,y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [51]:
knc_y_pr=knc.predict(T_test)

In [52]:
print(knc_y_pr)

[0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1
 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0
 0 1 1 0 0 0 1 0 1]


In [53]:
knc_score=knc.score(T_test,y_ts)

In [54]:
print(knc_score)

0.6156716417910447


In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
knc_conf_matrix=confusion_matrix(y_ts,knc_y_pr)

In [57]:
print(knc_conf_matrix)

[[124  33]
 [ 70  41]]


# SVC model

In [58]:
from sklearn.svm import SVC

In [59]:
svc=SVC()

In [60]:
svc.fit(T_train,y_tr)

C:\Users\sanjay.garje\AppData\Local\Continuum\anaconda3\envs\data science\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [61]:
svc_y_pr= svc.predict(T_test)

In [62]:
print(svc_y_pr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]


In [63]:
svc_score=svc.score(T_test,y_ts)

In [64]:
print(svc_score)

0.5895522388059702


In [65]:
from sklearn.metrics import confusion_matrix

In [66]:
svc_conf_matrix=confusion_matrix(y_ts,svc_y_pr)

In [67]:
print(svc_conf_matrix)

[[155   2]
 [108   3]]


# Decision tree model

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [69]:
Dtree=DecisionTreeClassifier()

In [70]:
Dtree.fit(T_train,y_tr)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [71]:
Dtree_y_pr=Dtree.score(T_test,y_ts)

In [72]:
print(Dtree_y_pr)

0.7649253731343284


In [73]:
DT_y_pr=Dtree.predict(T_test)

In [74]:
conf_mat_dt=confusion_matrix(y_ts,DT_y_pr)

In [75]:
print(conf_mat_dt)

[[125  32]
 [ 31  80]]


# Applying model on Testing data set

In [76]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

**Cleaning testing data and bringing it in format that of training data**

In [77]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [78]:
test_1=test.drop(['Name','Ticket','Cabin'],axis=1) ## droping non numeric and useless column which will not help in prediction

In [79]:
test_1.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S

In [80]:
## converting string/numeric catogorical columns Sex, Embarked and Pclass in binary number

In [81]:
from sklearn.preprocessing import LabelBinarizer
r=LabelBinarizer()

In [82]:
j1=r.fit_transform(test_1.Sex)
k1=r.fit_transform(test_1.Pclass)
l1=r.fit_transform(test_1.Embarked)

In [83]:
sex_t=pd.DataFrame(j1,columns=["sex_1"])

In [84]:
Pcl_t=pd.DataFrame(k1,columns=['Pcl_1','Pcl_2','Pcl_3'])

In [85]:
Emb_t=pd.DataFrame(l1,columns=['Emb_1','Emb_2','Emb_3'])

In [86]:
test_final=pd.concat([test_1,sex_t,Emb_t,Pcl_t],axis=1).drop(['Sex','Pclass','Embarked'],axis=1)

In [87]:
##Final Testing set after cleaning and making it prediction ready

In [88]:
test_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
PassengerId    418 non-null int64
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           417 non-null float64
sex_1          418 non-null int32
Emb_1          418 non-null int32
Emb_2          418 non-null int32
Emb_3          418 non-null int32
Pcl_1          418 non-null int32
Pcl_2          418 non-null int32
Pcl_3          418 non-null int32
dtypes: float64(2), int32(7), int64(3)
memory usage: 27.8 KB


In [89]:
test_final['Age']=test_final['Age'].fillna(value=test_final.Age.mean())

In [90]:
test_final=test_final.fillna(method='ffill')

In [91]:
test_final.head(3)

PassengerId   Age  SibSp  Parch    Fare  sex_1  Emb_1  Emb_2  Emb_3  Pcl_1  \
0          892  34.5      0      0  7.8292      1      0      1      0      0   
1          893  47.0      1      0  7.0000      0      0      0      1      0   
2          894  62.0      0      0  9.6875      1      0      1      0      0   

   Pcl_2  Pcl_3  
0      0      1  
1      0      1  
2      1      0

In [92]:
test_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
PassengerId    418 non-null int64
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           418 non-null float64
sex_1          418 non-null int32
Emb_1          418 non-null int32
Emb_2          418 non-null int32
Emb_3          418 non-null int32
Pcl_1          418 non-null int32
Pcl_2          418 non-null int32
Pcl_3          418 non-null int32
dtypes: float64(2), int32(7), int64(3)
memory usage: 27.8 KB


# Predicting on Final Tesing set

### 1) Logistic regression model

In [93]:
y_test_predict=logreg.predict(test_final)

In [94]:
print(y_test_predict)

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0
 1 1 1 1 1 1 0 1 0 0 0]


In [96]:
w=pd.DataFrame(y_test_predict)

In [98]:
w.to_csv('titanic1.csv')